/**
 * Documented omissions: upstream features intentionally not implemented in
 * Lexi's milestone-1 surface. Satisfies DoD §9 item 7 ("upstream features
 * have a Lexi counterpart OR documented omission").
 *
 * Rationale: Lexi v1 prioritises the §4 sections (Home -> Agents -> Connections
 * -> Workflows -> Vault -> Memory -> Cron -> Settings) per spec §10
 * risk-mitigation. Upstream routes outside that scope can be re-evaluated in
 * a future milestone. Each LEXI-OMIT marker below is recognised by
 * scripts/audit-upstream-features.mjs and converted into a "documented
 * omission" row in docs/lexi/UPSTREAM-PARITY.md.
 *
 * LEXI-OMIT: DELETE /api/agents/:slug
 * LEXI-OMIT: DELETE /api/agents/:slug/skills/:name
 * LEXI-OMIT: DELETE /api/background-tasks/:id
 * LEXI-OMIT: DELETE /api/brain/feeds/:name
 * LEXI-OMIT: DELETE /api/brain/sources/:slug
 * LEXI-OMIT: DELETE /api/builder/workflows/:id
 * LEXI-OMIT: DELETE /api/cli-tools/:cmd
 * LEXI-OMIT: DELETE /api/cron/:job/attachments/:filename
 * LEXI-OMIT: DELETE /api/cron/:name
 * LEXI-OMIT: DELETE /api/mcp-servers/:name
 * LEXI-OMIT: DELETE /api/memory/chunks/:id
 * LEXI-OMIT: DELETE /api/routines/:id
 * LEXI-OMIT: DELETE /api/settings/:key
 * LEXI-OMIT: DELETE /api/skills/:name
 * LEXI-OMIT: DELETE /api/unleashed/:name
 * LEXI-OMIT: DELETE /api/user-model/:slot
 * LEXI-OMIT: DELETE /api/workspace-dirs
 * LEXI-OMIT: DELETE /auth/sessions/:id
 * LEXI-OMIT: GET /api/activity
 * LEXI-OMIT: GET /api/advisor/analytics
 * LEXI-OMIT: GET /api/advisor/decisions
 * LEXI-OMIT: GET /api/advisor/effectiveness
 * LEXI-OMIT: GET /api/advisor/events
 * LEXI-OMIT: GET /api/advisor/reflection-trends
 * LEXI-OMIT: GET /api/advisor/status
 * LEXI-OMIT: GET /api/agent-heartbeats
 * LEXI-OMIT: GET /api/agents/:slug/activity
 * LEXI-OMIT: GET /api/agents/:slug/audit-summary
 * LEXI-OMIT: GET /api/agents/:slug/budget
 * LEXI-OMIT: GET /api/agents/:slug/detail
 * LEXI-OMIT: GET /api/agents/:slug/execution-log
 * LEXI-OMIT: GET /api/agents/:slug/health
 * LEXI-OMIT: GET /api/agents/:slug/kpis
 * LEXI-OMIT: GET /api/agents/:slug/pipeline
 * LEXI-OMIT: GET /api/agents/:slug/revisions
 * LEXI-OMIT: GET /api/agents/:slug/skills
 * LEXI-OMIT: GET /api/agents/:slug/stats
 * LEXI-OMIT: GET /api/agents/:slug/transcripts
 * LEXI-OMIT: GET /api/agents/compare
 * LEXI-OMIT: GET /api/analytics/tool-usage
 * LEXI-OMIT: GET /api/approvals
 * LEXI-OMIT: GET /api/assistant-preferences
 * LEXI-OMIT: GET /api/auth/anthropic/status
 * LEXI-OMIT: GET /api/autonomy
 * LEXI-OMIT: GET /api/available-tools
 * LEXI-OMIT: GET /api/background-tasks
 * LEXI-OMIT: GET /api/brain/artifacts/:id
 * LEXI-OMIT: GET /api/brain/connectors
 * LEXI-OMIT: GET /api/brain/credentials
 * LEXI-OMIT: GET /api/brain/feeds
 * LEXI-OMIT: GET /api/brain/library/search
 * LEXI-OMIT: GET /api/brain/runs
 * LEXI-OMIT: GET /api/brain/sources
 * LEXI-OMIT: GET /api/browse-dir
 * LEXI-OMIT: GET /api/budgets
 * LEXI-OMIT: GET /api/build/operations
 * LEXI-OMIT: GET /api/build/usage
 * LEXI-OMIT: GET /api/builder/mcp-discovery
 * LEXI-OMIT: GET /api/builder/workflows
 * LEXI-OMIT: GET /api/builder/workflows/:id
 * LEXI-OMIT: GET /api/channels/status
 * LEXI-OMIT: GET /api/claims
 * LEXI-OMIT: GET /api/claude-integrations
 * LEXI-OMIT: GET /api/cli-tools
 * LEXI-OMIT: GET /api/composio/status
 * LEXI-OMIT: GET /api/composio/toolkits
 * LEXI-OMIT: GET /api/cron
 * LEXI-OMIT: GET /api/cron/:job/attachments
 * LEXI-OMIT: GET /api/cron/:job/attachments/:filename
 * LEXI-OMIT: GET /api/cron/:job/prompt-history
 * LEXI-OMIT: GET /api/cron/broken-jobs
 * LEXI-OMIT: GET /api/cron/traces/:job
 * LEXI-OMIT: GET /api/discord/channels
 * LEXI-OMIT: GET /api/events
 * LEXI-OMIT: GET /api/fs/browse
 * LEXI-OMIT: GET /api/graph/visualization
 * LEXI-OMIT: GET /api/heartbeat
 * LEXI-OMIT: GET /api/heartbeat/agent/:slug
 * LEXI-OMIT: GET /api/heartbeat/control
 * LEXI-OMIT: GET /api/home-digest
 * LEXI-OMIT: GET /api/init
 * LEXI-OMIT: GET /api/logs
 * LEXI-OMIT: GET /api/mcp-permissions
 * LEXI-OMIT: GET /api/mcp-servers
 * LEXI-OMIT: GET /api/mcp-status
 * LEXI-OMIT: GET /api/memory
 * LEXI-OMIT: GET /api/memory/chunks/:id
 * LEXI-OMIT: GET /api/memory/chunks/:id/history
 * LEXI-OMIT: GET /api/memory/commitments
 * LEXI-OMIT: GET /api/memory/coverage
 * LEXI-OMIT: GET /api/memory/episodes
 * LEXI-OMIT: GET /api/memory/graph-stats
 * LEXI-OMIT: GET /api/memory/health
 * LEXI-OMIT: GET /api/memory/learnings
 * LEXI-OMIT: GET /api/memory/search
 * LEXI-OMIT: GET /api/memory/session-bridge
 * LEXI-OMIT: GET /api/memory/supersedes
 * LEXI-OMIT: GET /api/memory/writes/recent
 * LEXI-OMIT: GET /api/metrics
 * LEXI-OMIT: GET /api/metrics/usage
 * LEXI-OMIT: GET /api/office
 * LEXI-OMIT: GET /api/ping
 * LEXI-OMIT: GET /api/plans
 * LEXI-OMIT: GET /api/plans/:date
 * LEXI-OMIT: GET /api/plans/diff
 * LEXI-OMIT: GET /api/plans/today
 * LEXI-OMIT: GET /api/profiles
 * LEXI-OMIT: GET /api/projects
 * LEXI-OMIT: GET /api/recall-traces
 * LEXI-OMIT: GET /api/recall-traces/:id
 * LEXI-OMIT: GET /api/remote-access
 * LEXI-OMIT: GET /api/routines
 * LEXI-OMIT: GET /api/routines/:id
 * LEXI-OMIT: GET /api/routines/:id/runs
 * LEXI-OMIT: GET /api/routines/cli-tools
 * LEXI-OMIT: GET /api/routines/mcp-tools
 * LEXI-OMIT: GET /api/routing-audit
 * LEXI-OMIT: GET /api/salesforce/status
 * LEXI-OMIT: GET /api/salesforce/sync-history
 * LEXI-OMIT: GET /api/self-improve
 * LEXI-OMIT: GET /api/sessions
 * LEXI-OMIT: GET /api/sessions/:key/messages
 * LEXI-OMIT: GET /api/sessions/:key/usage
 * LEXI-OMIT: GET /api/settings
 * LEXI-OMIT: GET /api/setup/discord/invite-url
 * LEXI-OMIT: GET /api/skills
 * LEXI-OMIT: GET /api/skills/:name
 * LEXI-OMIT: GET /api/skills/pending
 * LEXI-OMIT: GET /api/slack/channels
 * LEXI-OMIT: GET /api/status
 * LEXI-OMIT: GET /api/team/agents
 * LEXI-OMIT: GET /api/team/messages
 * LEXI-OMIT: GET /api/team/pending-requests
 * LEXI-OMIT: GET /api/team/status
 * LEXI-OMIT: GET /api/team/topology
 * LEXI-OMIT: GET /api/timers
 * LEXI-OMIT: GET /api/tool-preferences
 * LEXI-OMIT: GET /api/unleashed
 * LEXI-OMIT: GET /api/unleashed/:name/status
 * LEXI-OMIT: GET /api/user-model
 * LEXI-OMIT: GET /api/vault-file
 * LEXI-OMIT: GET /api/vault-files
 * LEXI-OMIT: GET /api/version
 * LEXI-OMIT: GET /api/voice/audio/:hash
 * LEXI-OMIT: GET /api/webhook-actions
 * LEXI-OMIT: GET /api/workspace-dirs
 * LEXI-OMIT: GET /auth/logout
 * LEXI-OMIT: GET /auth/sessions
 * LEXI-OMIT: GET /icon.svg
 * LEXI-OMIT: GET /manifest.json
 * LEXI-OMIT: GET /sw.js
 * LEXI-OMIT: POST /api/agents
 * LEXI-OMIT: POST /api/agents/:slug/revisions/:id/restore
 * LEXI-OMIT: POST /api/agents/:slug/skills
 * LEXI-OMIT: POST /api/agents/:slug/status
 * LEXI-OMIT: POST /api/approvals/:id/:action
 * LEXI-OMIT: POST /api/auth/anthropic/login
 * LEXI-OMIT: POST /api/auth/anthropic/wait
 * LEXI-OMIT: POST /api/background-tasks/:id/cancel
 * LEXI-OMIT: POST /api/bot/derive-invite
 * LEXI-OMIT: POST /api/brain/credentials
 * LEXI-OMIT: POST /api/brain/feeds
 * LEXI-OMIT: POST /api/brain/feeds/:name/run
 * LEXI-OMIT: POST /api/brain/mcp/probe
 * LEXI-OMIT: POST /api/brain/seed/commit
 * LEXI-OMIT: POST /api/brain/seed/commit/stream
 * LEXI-OMIT: POST /api/brain/seed/preview
 * LEXI-OMIT: POST /api/brain/seed/preview/stream
 * LEXI-OMIT: POST /api/brain/seed/upload
 * LEXI-OMIT: POST /api/brain/sources
 * LEXI-OMIT: POST /api/brain/sources/:slug/run
 * LEXI-OMIT: POST /api/budgets/1m
 * LEXI-OMIT: POST /api/budgets/doctor-fix
 * LEXI-OMIT: POST /api/budgets/preset
 * LEXI-OMIT: POST /api/budgets/safe
 * LEXI-OMIT: POST /api/budgets/set
 * LEXI-OMIT: POST /api/builder/chat
 * LEXI-OMIT: POST /api/builder/chat/stream
 * LEXI-OMIT: POST /api/builder/reset
 * LEXI-OMIT: POST /api/builder/runs/:runId/cancel
 * LEXI-OMIT: POST /api/builder/save
 * LEXI-OMIT: POST /api/builder/test
 * LEXI-OMIT: POST /api/builder/workflows
 * LEXI-OMIT: POST /api/builder/workflows/:id/dry-run
 * LEXI-OMIT: POST /api/builder/workflows/:id/run
 * LEXI-OMIT: POST /api/builder/workflows/:id/save-from-drawflow
 * LEXI-OMIT: POST /api/builder/workflows/:id/test
 * LEXI-OMIT: POST /api/builder/workflows/:id/validate
 * LEXI-OMIT: POST /api/chat
 * LEXI-OMIT: POST /api/chat/stream
 * LEXI-OMIT: POST /api/claims/:id/dismiss
 * LEXI-OMIT: POST /api/claims/:id/mark-failed
 * LEXI-OMIT: POST /api/claims/:id/mark-verified
 * LEXI-OMIT: POST /api/cli-tools
 * LEXI-OMIT: POST /api/composio/connections/:id/rename
 * LEXI-OMIT: POST /api/composio/refresh
 * LEXI-OMIT: POST /api/composio/toolkits/:slug/authorize
 * LEXI-OMIT: POST /api/composio/toolkits/:slug/disconnect
 * LEXI-OMIT: POST /api/cron
 * LEXI-OMIT: POST /api/cron/:job/attachments
 * LEXI-OMIT: POST /api/cron/:name/toggle
 * LEXI-OMIT: POST /api/cron/broken-jobs/:jobName/apply-fix
 * LEXI-OMIT: POST /api/cron/broken-jobs/:jobName/dismiss-diagnosis
 * LEXI-OMIT: POST /api/cron/run/:job
 * LEXI-OMIT: POST /api/cron/train
 * LEXI-OMIT: POST /api/dashboard/restart
 * LEXI-OMIT: POST /api/heartbeat/queue
 * LEXI-OMIT: POST /api/launch
 * LEXI-OMIT: POST /api/leads/import
 * LEXI-OMIT: POST /api/mcp-servers
 * LEXI-OMIT: POST /api/memory/chunks/:id/pin
 * LEXI-OMIT: POST /api/memory/chunks/:id/restore
 * LEXI-OMIT: POST /api/memory/commitments/action
 * LEXI-OMIT: POST /api/memory/health/action
 * LEXI-OMIT: POST /api/memory/learnings/action
 * LEXI-OMIT: POST /api/memory/quick-add
 * LEXI-OMIT: POST /api/plans/apply
 * LEXI-OMIT: POST /api/profiles/switch
 * LEXI-OMIT: POST /api/projects/link
 * LEXI-OMIT: POST /api/projects/unlink
 * LEXI-OMIT: POST /api/remote-access/disable
 * LEXI-OMIT: POST /api/remote-access/enable
 * LEXI-OMIT: POST /api/remote-access/regenerate-token
 * LEXI-OMIT: POST /api/remote-access/toggle-auto-post
 * LEXI-OMIT: POST /api/restart
 * LEXI-OMIT: POST /api/routines
 * LEXI-OMIT: POST /api/routines/:id/dry-run
 * LEXI-OMIT: POST /api/routines/:id/run
 * LEXI-OMIT: POST /api/routines/:id/test
 * LEXI-OMIT: POST /api/routines/:id/toggle
 * LEXI-OMIT: POST /api/runagent/test
 * LEXI-OMIT: POST /api/self-improve/apply/:id
 * LEXI-OMIT: POST /api/self-improve/deny/:id
 * LEXI-OMIT: POST /api/self-improve/run
 * LEXI-OMIT: POST /api/sessions/:key/clear
 * LEXI-OMIT: POST /api/setup/discord/save
 * LEXI-OMIT: POST /api/setup/discord/test
 * LEXI-OMIT: POST /api/skills
 * LEXI-OMIT: POST /api/skills/pending/:name/approve
 * LEXI-OMIT: POST /api/skills/pending/:name/reject
 * LEXI-OMIT: POST /api/stop
 * LEXI-OMIT: POST /api/team/message
 * LEXI-OMIT: POST /api/team/request
 * LEXI-OMIT: POST /api/timers/:id/cancel
 * LEXI-OMIT: POST /api/unleashed/:name/cancel
 * LEXI-OMIT: POST /api/user-model/seed
 * LEXI-OMIT: POST /api/workspace-dirs
 * LEXI-OMIT: POST /auth/login
 * LEXI-OMIT: POST /webhook-action/:source
 * LEXI-OMIT: POST /webhook/:slug
 * LEXI-OMIT: PUT /api/agents/:slug
 * LEXI-OMIT: PUT /api/assistant-preferences
 * LEXI-OMIT: PUT /api/builder/workflows/:id
 * LEXI-OMIT: PUT /api/cli-tools/:cmd
 * LEXI-OMIT: PUT /api/cron/:name
 * LEXI-OMIT: PUT /api/heartbeat/control
 * LEXI-OMIT: PUT /api/mcp-servers/:name
 * LEXI-OMIT: PUT /api/memory/chunks/:id
 * LEXI-OMIT: PUT /api/routines/:id
 * LEXI-OMIT: PUT /api/settings/:key
 * LEXI-OMIT: PUT /api/tool-preferences
 * LEXI-OMIT: PUT /api/user-model/:slot
 */
export const UPSTREAM_OMISSIONS_DOCUMENTED = true;
